### ISSUE TITLE
BUG: mod doesnt clear old positions for the experimentation table experiment 

### ISSUE THREAD

**Issue by Teh404Gal** [kevinthegreat1/SkyblockMod-Fabric#1]
title + the bug also makes it impossible to do any experiment except super pairs without restarting

**Comment by kevinthegreat1** [comment]
Thanks for reporting. I have identified the issue and am implementing a fix. I will update the releases as soon as possible.

**Comment by kevinthegreat1** [comment]
Fixed with release 1.7.2. Please take a look.
