### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by Aces-and-Jacks** [kevinthegreat1/SkyblockMod-Fabric#3]
a help command to show commands for just this mod in particular

**Comment by kevinthegreat1** [comment]
Ok, this sounds like a good idea. I will do at some point.

**Comment by Aces-and-Jacks** [comment]
since you added the help command I'll close this issue. Tho it was only for 1.19.3

**Comment by kevinthegreat1** [comment]
Is there a reason that you are not updating? I can back port this pretty easily.

**Comment by Aces-and-Jacks** [comment]
not all the mods i use aren't updated yet

**Comment by kevinthegreat1** [comment]
That should be resolved very quickly. In that case, I don't see a point in backporting this and never being used after a few days.

**Comment by Aces-and-Jacks** [comment]
Well yeah that's true

**Comment by Aces-and-Jacks** [comment]
Well yeah that's true
