### ISSUE TITLE
[bug] breaks view bobbing

### ISSUE THREAD

**Issue by saefty-git** [kevinthegreat1/SkyblockMod-Fabric#6]
SkyblockMod breaks the default screen shake from the view bobbing setting. MC is 1.19.4 latest fabric and SkyblockMod with no other mods. Tested on both 1.8.2 and the latest 1.9.0-alpha. 

I couldn't find any direct references to anything related to view bobbing or vanilla settings in the repo, but I suspect the issue results from some kind of overwritten rendering or options implementation that skips view bobbing and potentially other related vanilla graphics settings. Something to note is that the player's hand still bobs with view bobbing enabled, it's just the screen shake that is broken; so it's probably a rendering issue rather than an options conflict. 

This issue does not happen with the other 1.19 Skyblock mod 'Skyblocker' if you need a point of comparison.

**Comment by saefty-git** [comment]
This same issue happens even with all options turned off in the config.

**Comment by kevinthegreat1** [comment]
This seems to be caused by [Renderer](https://github.com/0x3C50/Renderer). I submitted a bug report [here](https://github.com/0x3C50/Renderer/issues/21), and please add any details. Thanks for reporting.

**Comment by 0x3C50** [comment]
This has been resolved, can be closed
