### ISSUE TITLE
/g, /f, /p commands compatibility issue

### ISSUE THREAD

**Issue by z1beee** [kevinthegreat1/SkyblockMod-Fabric#7]
The mod replaces basic skyblock commands such as /g, /p and /f with warp shortcuts, not allowing user to change settings of groups without typing full command (/guild, /friends etc). Since other shortcuts exist, I think it's not necessary to have them as well.

**Comment by kevinthegreat1** [comment]
I did not know the shortcuts conflict with existing commands. Is it just `/f`, `/g`, and `/p`? I will remove the shortcuts.

**Comment by kevinthegreat1** [comment]
Renamed `/f` and `/g`. `/p` didn't exist since commit `ec36f6cd` from last year.
