### ISSUE TITLE
Please add price info for auction house (New feature or request)

### ISSUE THREAD

**Issue by pradeepdhibar** [kevinthegreat1/SkyblockMod-Fabric#8]
Please add price info for auction house

**Comment by kevinthegreat1** [comment]
Use [Skyblocker](https://modrinth.com/mod/skyblocker-liap), a similar mod with more features.

**Comment by pradeepdhibar** [comment]
Because it's too more features my pc lagging 😞. So i use this mod no more features just basic .

**Comment by kevinthegreat1** [comment]
It shouldn't lag, you can join the discord for help.
